development:
  adapter: mysql
  encoding: latin1
  reconnect: false
  database: localisation
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql
  reconnect: false
  database: heroku_6bcc44798b96f42
  pool: 5
  username: bded8f9224b3ed
  password: 86752475
  host:us-cdbr-iron-east-02.cleardb.net
test:
  adapter: mysql
  encoding: latin1
  reconnect: false
  database: localisation
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

